### ISSUE TITLE
CI: Migrate from LGTM.COM to GitHub Actions CodeQL

### ISSUE THREAD

**Issue by jimklimov** [networkupstools/nut#1726]
LGTM.com is deprecated and soon to be offlined: https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

Apparent old LGTM config per https://github.com/networkupstools/nut/blob/master/.lgtm.yml :
````
path_classifiers:
  template:
  - exclude: "**/*.py.in"
  - exclude: "**/NUT-Monitor.in"
queries:
- exclude: "cpp/fixme-comment"
- exclude: "python/fixme-comment"
extraction:
  python:
    after_prepare:
    - "./autogen.sh"
    - "./configure --without-docs"
    python_setup:
      version: "2"
      setup_py: false
    index:
      filters:
      - include: "**/*.py.in"
      - include: "**/NUT-Monitor.in"
      - include: "**/*.py"
      - include: "**/NUT-Monitor"
````

A first shot at https://github.com/networkupstools/nut/blob/master/.github/workflows/codeql.yml failed to find Python sources with the new action.
* https://github.com/networkupstools/nut/commit/ce7a01d7d8fbe8a7883975bf977637d662db1e53
