### ISSUE TITLE
[Cyberpower PR1500ELCD] Various regression with latest updates

### ISSUE THREAD

**Issue by sblantipodi** [networkupstools/nut#1969]
hello... I'm using the NUT addon since years now.
it works super awesome on my CyberPower PR1500ELCD using USB connected to my Pi4 running Home Assistant OS

Since latest udpates some entities stopped working.
sensor.myups_output_voltage
is fixed at 265V and does not move from that value.

it worked before, now it shows 265V no matter what the real output voltage is.

**Comment by sblantipodi** [comment]
can this fix 
https://github.com/networkupstools/nut/issues/439
helps on this issue?

**Comment by jimklimov** [comment]
I think there were some changes to that area after 2.8.0 release. Did you install a custom build or the release?

**Comment by sblantipodi** [comment]
@jimklimov I'm using the one inside the Home Assistant NUT addon:
Network UPS Tools - Generic HID driver 0.47 (2.8.0)
but there are other users complaining about the same issue on a non custom build.

**Comment by jimklimov** [comment]
Thanks. The practical side of the question is whether that issue did get fixed in existing NUT master-branch codebase, as I suspect it might have been after 2.8.0 release. Eventually when other bug-fixes are collected and 2.8.1 is cut, it would get solved also for other people's "non custom builds" :)

So if you would have a chance to check with newer NUT (whether by building a custom HA plugin binary - see wiki page https://github.com/networkupstools/nut/wiki/Building-NUT-integration-for-Home-Assistant for community-contributed guidelines, or in its host OS, or by dedicating a computer for a while to make and run the build) - it would be much appreciated. I have no experience with HA itself so can't help much there. With "common" builds in an OS, you can avoid installing the results and can run the driver from the build workspace to check if it works better than the older release snapshot - see https://github.com/networkupstools/nut/wiki/Building-NUT-for-in%E2%80%90place-upgrades-or-non%E2%80%90disruptive-tests for details and suggestions about that.

**Comment by sblantipodi** [comment]
hi @jimklimov it seems that the addon I'm using uses the nut=2.8.0-7 from the apt repo.
https://github.com/hassio-addons/addon-nut/blob/eb23aec5b591aab90a10a8189bd039c954ae5ab5/nut/Dockerfile#LL10C9-L10C20

I'm not able to build an addon currently and I have no time to learn it in this moment... hope to see someone else that could help here :)

**Comment by ingcicala** [comment]
I reported the same bug on HA forum

**Comment by KameDomotics** [comment]
I have the same problem, load sensor and output voltage sensor does not work. 
How can I fix it please?
(Home Assistant 2023.7.3 / NUT add on 0.12.0)
Thanks

**Comment by sblantipodi** [comment]
I switched to docker compose image and same problem:
```
  nut-upsd:
    container_name: nut-upsd
    image: instantlinux/nut-upsd
    environment:
    - "PORT=/dev/bus/usb/001/003"
    - "NAME=Cyberpower_PR1500ELCD"
    - "DESCRIPTION=Cyberpower_PR1500ELCD"
    - "DRIVER=usbhid-ups"
    - "API_USER=admin"
    - "API_PASSWORD=mypwd"
    privileged: true
    ports:
      - 3493:3493
    restart: always
```

is there any interest in fixing this?
