### ISSUE TITLE
Are there more readings with usb rather than snmp? Eaton 5P 850

### ISSUE THREAD

**Issue by Zuendapp** [networkupstools/nut#2443]
Hi there,

my colleague uses the same Eaton 5P with Network UPS Tools as I, the only difference is that I'm using it with SNMP and he with a USB connection.
So he's getting about 40 readings and mine "only" 26.

Thank you very much!

BR

**Comment by jimklimov** [comment]
This is quite possible, also note that depending on Eaton model, several vendor-extended MIB mappings can apply to the same device and support sometimes not-overlapping data sets and/or represent same information with different precision.

Which one has more - that depends on the information reported by the device and by readiness of the NUT drivers to understand it (protocol-wise and mappings specifically). So this can vary also between versions of firmwares of the UPS and its management card, and what they report over different protocols internally and externally.

For clarity, do both of you use the same NUT version (and a recent 2.8.x one, at that)?

**Comment by Zuendapp** [comment]
Hi @jimklimov :),

we use both the latest homeassistant addon in version 0.13.0 which show in the logs following NUT version (nut:all 2.8.0-7).

My config:

```
users:
  - username: admin
    password: P@ssword
    instcmds:
      - all
    actions: []
devices:
  - name: Eaton5P850i
    driver: snmp-ups
    port: 192.168.1.20
    log_level: info
    config:
      - snmp_version = v1
      - community = private
mode: netserver
shutdown_host: "false"
log_level: info
```



The only thing what is different is that I'm using the Tower version of the USV and he the Rack version (both 5P 850).

My installed Firmware versions are:

SNMP-Card (Network M2): 3.1.12
USV Firmware Version: 3.18.0035


Thank you!

BR
