### ISSUE TITLE
Supported device: GreenCell UPS07 (800VA)

### ISSUE THREAD

**Issue by yannick-Lapierre** [networkupstools/nut#2470]
Hi,
I managed to set up NUT for GreenCell UPS07 (800VA).
Configuration:
``` YAML
- name: myups
  driver: nutdrv_qx
  port: auto
  config: []
```

Entities (sorry, it's French):
![image](https://github.com/networkupstools/nut/assets/37714992/b4c53b11-f583-47ca-a446-a76162478f2b)
