### ISSUE TITLE
Nut UPS and polling interval in Home Assistant

### ISSUE THREAD

**Issue by sblantipodi** [networkupstools/nut#2993]
Hi there,
my NUT server is configured to poll the UPS every 10 minutes and it works well...
The NUT UPS integration is polling the sensors every minute, I tried to create an automation that update the sensors every 10 seconds but it doesn't work, it continue to poll the sensors every minute.

Is there a way to fix this?

It worked well before.

my ups.conf is like this:

```
[Cyberpower_PR1500ELCD]
        driver = usbhid-ups
        port = auto
        desc = Cyberpower_PR1500ELCD
        pollinterval = 10
        pollfreq = 5
        vendorid = 0764
        productid = 0601
```

I think that this is a problem of Home Assistent but I hope to see the HA users here that can help.

**Comment by sblantipodi** [comment]
this is the automation I have
```
  - id: '1750594741483'
    alias: Cyberpower_polling_automation
    description: ''
    triggers:
    - trigger: time_pattern
      seconds: '10'
    conditions: []
    actions:
    - action: homeassistant.update_entity
      data:
        entity_id:
        - sensor.cyberpower_pr1500elcd_status
        - sensor.cyberpower_watt_load
        - sensor.cyberpower_pr1500elcd_battery_charge
        - sensor.cyberpower_pr1500elcd_battery_chemistry
        - sensor.cyberpower_pr1500elcd_battery_manuf_date
        - sensor.cyberpower_pr1500elcd_battery_runtime
        - sensor.cyberpower_pr1500elcd_battery_voltage
        - sensor.cyberpower_pr1500elcd_beeper_status
        - sensor.cyberpower_pr1500elcd_input_voltage
        - sensor.cyberpower_pr1500elcd_load
        - sensor.cyberpower_pr1500elcd_load_restart_delay
        - sensor.cyberpower_pr1500elcd_load_start_timer
        - sensor.cyberpower_pr1500elcd_low_battery_runtime
        - sensor.cyberpower_pr1500elcd_low_battery_setpoint
        - sensor.cyberpower_pr1500elcd_nominal_battery_voltage
        - sensor.cyberpower_pr1500elcd_nominal_input_voltage
        - sensor.cyberpower_pr1500elcd_nominal_real_power
        - sensor.cyberpower_pr1500elcd_output_voltage
        - sensor.cyberpower_pr1500elcd_self_test_result
        - sensor.cyberpower_pr1500elcd_ups_shutdown_delay
        - sensor.cyberpower_runtime
        - sensor.cyberpower_pr1500elcd_status_data
        - sensor.cyberpower_pr1500elcd_load_shutdown_timer
        - sensor.cyberpower_pr1500elcd_warning_battery_setpoint
    mode: single
```

![Image](https://github.com/user-attachments/assets/d678f075-7c02-4d09-b3a4-95a1366e6c16)
